openapi: 3.0.3
info:
  description: This similarity score api for MassBank3 calculates the spectral similarity
    between the spectrum defined in the query peak list and the reference spectra
    list.
  title: Similarity score api for MassBank3
  version: 0.0.1
servers:
- url: /
paths:
  /similarity:
    post:
      operationId: similarity_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_similarity_post_request'
        description: a similarity job
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/similarity_score_list'
          description: Similarity job successfully calculated.
        "400":
          content:
            application/json:
              example: Can not read peak list.
              schema:
                type: string
          description: The server can not process the input.
        "503":
          content:
            application/json:
              example: Server is busy with preprocessing.
              schema:
                type: string
          description: The server is not ready to handle the request.
        "500":
          content:
            application/json:
              example: some error
              schema:
                type: string
          description: The server encountered an unexpected condition.
      summary: Create a new similarity calculation.
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /version:
    get:
      operationId: version_get
      responses:
        "200":
          content:
            application/json:
              example: cosine similarity 1.0.0
              schema:
                type: string
          description: version string
      summary: Get the version string of the implementation.
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    peak_list:
      description: the peak list of the query spectrum
      example:
      - mz: 147.063
        intensity: 121.684
      - mz: 303.05
        intensity: 10000.0
      - mz: 449.108
        intensity: 657.368
      - mz: 465.102
        intensity: 5884.21
      - mz: 611.161
        intensity: 6700.0
      items:
        $ref: '#/components/schemas/peak_list_inner'
      title: peak_list
      type: array
    reference_spectra_list:
      description: "the reference spectra list, list of ACCESSION strings"
      example:
      - MSBNK-IPB_Halle-PB001341
      - MSBNK-IPB_Halle-PB006202
      - MSBNK-IPB_Halle-PB006203
      - MSBNK-IPB_Halle-PB001342
      - MSBNK-IPB_Halle-PB001343
      items:
        type: string
      title: reference_spectra_list
      type: array
    similarity_score_list:
      description: "the similarity score list, list of similarity scores"
      items:
        $ref: '#/components/schemas/similarity_score_list_inner'
      type: array
    _similarity_post_request:
      properties:
        peak_list:
          description: the peak list of the query spectrum
          example:
          - mz: 147.063
            intensity: 121.684
          - mz: 303.05
            intensity: 10000.0
          - mz: 449.108
            intensity: 657.368
          - mz: 465.102
            intensity: 5884.21
          - mz: 611.161
            intensity: 6700.0
          items:
            $ref: '#/components/schemas/peak_list_inner'
          title: peak_list
          type: array
        reference_spectra_list:
          description: "the reference spectra list, list of ACCESSION strings"
          example:
          - MSBNK-IPB_Halle-PB001341
          - MSBNK-IPB_Halle-PB006202
          - MSBNK-IPB_Halle-PB006203
          - MSBNK-IPB_Halle-PB001342
          - MSBNK-IPB_Halle-PB001343
          items:
            type: string
          title: reference_spectra_list
          type: array
      title: _similarity_post_request
      type: object
    peak_list_inner:
      description: a peak with m/z and intensity
      properties:
        mz:
          description: m/z value
          title: mz
          type: number
        intensity:
          description: intensity value
          title: intensity
          type: number
      title: peak_list_inner
      type: object
    similarity_score_list_inner:
      example:
      - accession: MSBNK-IPB_Halle-PB001341
        similarity_score: 0.3
      - accession: MSBNK-IPB_Halle-PB006202
        similarity_score: 0.5
      - accession: MSBNK-IPB_Halle-PB006203
        similarity_score: 0.5
      - accession: MSBNK-IPB_Halle-PB001342
        similarity_score: 0.9
      - accession: MSBNK-IPB_Halle-PB001343
        similarity_score: 0.8
      properties:
        accession:
          type: string
        similarity_score:
          type: number
      title: similarity_score_list_inner
      type: object
